config/routes.rb
Jobapp::Application.routes.draw do
  devise_for :users
  root 'static_pages#home'
  get 'users/:user_id/interviews' => 'interviews#index', as: :interviews

  resources :users, shallow: true do
      resources :applications, shallow: true do
        resources :interviews
      end  
  end    

end

app/models/application.rb
class Application < ActiveRecord::Base
  belongs_to :user
  has_many :interviews, :dependent => :destroy
  validates :position, presence: true
end 

app/models/interview.rb
class Interview < ActiveRecord::Base
  belongs_to :application
  validates :date_interviewed, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :applications
  has_many :interviews, through: :applications     
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/applications_controller.rb
class ApplicationsController < ApplicationController
  before_action :set_application, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!

  def index
    @user = User.find(params[:user_id]) 
    @applications = current_user.applications.order(date_applied: :desc)
  end

  def create
    @application = current_user.applications.new(application_params)

    respond_to do |format|
      if @application.save
        format.html { redirect_to @application, notice: 'Application was successfully created.' }
        format.json { render action: 'show', status: :created, location: @application }
      else
        format.html { render action: 'new' }
        format.json { render json: @application.errors, status: :unprocessable_entity }
      end
    end
  end

  def new
    @user = User.find(params[:user_id])
    @application = @user.applications.new
  end 

  def edit
  end
    
  def show
  end

  def update
    respond_to do |format|
      if @application.update(application_params)
        format.html { redirect_to @application, notice: 'Application was successfully updated.' }       
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @application.errors, status: :unprocessable_entity }
      end
    end
  end
  
  def destroy
    @application.destroy
    respond_to do |format|
      format.html { redirect_to user_url(@user) }
      format.json { head :no_content }
    end
    redirect_to @user, notice: "Application Deleted"    
  end 

  private
    def set_application
      @application = Application.find(params[:id])
    end 

  def application_params
    params.require(:application).permit(:position, :company, :date_applied, :link, :description, :notes, :contact_name, :contact_address, :contact_phone, :contact_email, :user_id)
  end 
end

app/controllers/interviews_controller.rb
class InterviewsController < ApplicationController
  before_action :set_interview, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!

  def index 
    @interviews = current_user.interviews
    @interviews_by_date = @interviews.group_by(&:date_interviewed) 
    @date = params[:date] ? Date.parse(params[:date]) : Date.today
  end

  def create
    @application = Application.find(params[:application_id])
    @interview = @application.interviews.new(interview_params)

    respond_to do |format|
      if @interview.save
        format.html { redirect_to @interview, notice: 'Interview was successfully created.' }
        format.json { render action: 'show', status: :created, location: @interview }
      else
        format.html { render action: 'new' }
        format.json { render json: @interview.errors, status: :unprocessable_entity }
      end
    end
  end

  def new
      @application = Application.find(params[:application_id])
      if current_user == @application.user  
      @interview = @application.interviews.new
    else
      redirect_to "/"
    end 
  end 

  def edit
  end
    
  def show  
  end

  def update
    respond_to do |format|
      if @interview.update(interview_params)
        format.html { redirect_to @interview, notice: 'Interview was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @interview.errors, status: :unprocessable_entity }
      end
    end
  end
  
  def destroy
    @interview.destroy
    respond_to do |format|
      format.html { redirect_to interviews_url(current_user) }
      format.json { head :no_content }
    end   
  end 

  private
    def set_interview
      @interview = Interview.find(params[:id])
    end 

  def interview_params
    params.require(:interview).permit(:date_interviewed, :kind, :notes, :interview_time, :application_id, :user_id)
  end 
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    render :layout => "home"
  end 
end 

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/calendar_helper.rb
module CalendarHelper
  def calendar(date = Date.today, &block)
    Calendar.new(self, date, block).table
  end

  class Calendar < Struct.new(:view, :date, :callback)
    HEADER = %w[Monday Tuesday Wednesday Thursday Friday Saturday Sunday]
    START_DAY = :monday

    delegate :content_tag, to: :view

    def table
      content_tag :table, class: "table-bordered" do
        header + week_rows
      end
    end

    def header
      content_tag :tr do
        HEADER.map { |day| content_tag :th, day }.join.html_safe
      end
    end

    def week_rows
      weeks.map do |week|
        content_tag :tr do
          week.map { |day| day_cell(day) }.join.html_safe
        end
      end.join.html_safe
    end

    def day_cell(day)
      content_tag :td, view.capture(day, &callback), class: day_classes(day)
    end

    def day_classes(day)
      classes = []
      classes << "today" if day == Date.today
      classes << "notmonth" if day.month != date.month
      classes.empty? ? nil : classes.join(" ")
    end

    def weeks
      first = date.beginning_of_week(START_DAY)
      last = date.end_of_week(START_DAY)
      (first..last).to_a.in_groups_of(7)
    end
  end
end

app/views/applications/_form.html.erb
<%= form_for([@user, @application]) do |f| %>
<div class="col-lg-8">  
  <div class="form-group">
    <%= f.label :position %><br>
    <%= f.text_field :position, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :company %><br>
    <%= f.text_field :company, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :date_applied %><br>
    <%= f.date_field :date_applied, class: "form-control", input: "date" %>
  </div>  
  <div class="form-group">
    <%= f.label :link %><br>
    <%= f.text_field :link, class: "form-control" %>
  </div>  
  <div class="form-group">
    <%= f.label :description %><br>
    <%= f.text_area :description, class: "form-control", rows: "5" %>
  </div>
  <div class="form-group">
    <%= f.label :notes %><br>
    <%= f.text_area :notes, class: "form-control",  rows: "5" %>
  </div>       
  <h4>Contact Info</h4>
  <div class="form-group">
    <%= f.label :contact_name, "Name" %><br>
    <%= f.text_field :contact_name, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :contact_email, "Email" %><br>
    <%= f.text_field :contact_email, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :contact_phone, "Phone Number" %><br>
    <%= f.telephone_field :contact_phone, class: "form-control" %>
  </div>        
  <div class="form-group">
    <%= f.label :contact_address, "Address" %><br>
    <%= f.text_area :contact_address, class: "form-control",  rows: "3" %>
  </div>  
</div>         
<div class="col-lg-12">
    <%= f.submit "Submit", class: "btn btn-large btn-primary" %>    
</div>
<% end %>

app/views/applications/edit.html.erb
<h1>Edit Application Info</h1>

<%= render 'form' %>
<div class="col-lg-12">
  <%= link_to 'Cancel', application_path(@application) %>
</div>  

app/views/applications/index.html.erb
<div class="col-lg-12">
  <div class= "col-lg-9">
    <h2>Your Job Applications</h2>
  </div>
  <div class="col-lg-3">
    <span id="newApplicationButton"><%= link_to "Add a New Application", new_user_application_path, class: "btn btn-warning btn" %></span>
  </div>  
</div>
<div id=applicationIndex class="col-lg-12">
<% @applications.each do |application| %>
  <div class="col-lg-8">
    <h3><%= link_to application.position, application %>: <%= application.company %></h3>
    <p>Applied: <%= application.date_applied %></p>
  </div>
  <div class="col-lg-4">
    <% if application.interviews.count == 0 %>
    <% else %>
    <h4>Interviews</h4>
      <% application.interviews.each do |interview| %>
      <p><%= link_to interview.kind, interview %> - <%= interview.date_interviewed %></p>
      <% end %>
    <% end %>  
  </div>
  <div class="col-lg-12">
    <hr>
  </div>
<% end %>
</div>
<div class="col-lg-12">
<%= link_to "New Application", new_user_application_path %>
</div>

app/views/applications/new.html.erb
<title>Track new job application</title>
<h1>Track new job application</h1>
<%= render 'form' %>
<div class="col-lg-12">
  <%= link_to 'Cancel', user_applications_path(@user) %>
</div>

app/views/applications/show.html.erb
<h2><%= @application.position %></h2>
<div class="col-lg-8">
  <h3><%= @application.company %> | Applied: <%= @application.date_applied %></h3>
  <% if @application.description? %>
  <h4>Description</h4>
  <p><%= simple_format @application.description %></p>
  <% end %>
  <% if @application.notes? %>
  <h4>Notes</h4>
  <p><%= simple_format @application.notes %></p>
  <% end %>
  <% if @application.link? %>
  <h4>Website</h4>
  <p><%= link_to @application.link, @application.link %></p>
  <% end %>
  <% if @application.interviews.count == 0 %>
  <% else %>
  <h4>Interviews</h4>
  <ul>
    <% @application.interviews.each do |interview| %>
    <li><%= link_to "#{interview.kind}: ", interview_path(interview) %> <%= interview.date_interviewed %></li>
    <% end %>
  </ul>
  <% end %>
</div>
<% if @application.contact_name? || @application.contact_email? || @application.contact_phone? || @application.contact_address? %>
<aside class="col-lg-4"> 
  <h3>Contact</h3>
  <% if @application.contact_name? %>
  <p><%= @application.contact_name %></p>
  <% end %>
  <% if @application.contact_email? %>
  <h4>Email</h4>
  <p><%= @application.contact_email %></p>
  <% end %>
  <% if @application.contact_phone? %>
  <h4>Phone Number</h4>
  <p><%= simple_format @application.contact_phone %></p>
  <% end %>
  <% if @application.contact_address? %>  
  <h4>Address</h4>
  <p><%= simple_format @application.contact_address %></p>
  <% end %>
</aside>
<% end %>
<div class="col-lg-12">
<small><%= link_to "View All Applications", user_applications_path(@application.user_id) %> | 
<%= link_to "Add a new interview", new_application_interview_path(@application) %>
<br>
<small><%= link_to 'Edit', edit_application_path %> | 
<%= link_to 'Destroy', application_path, method: :delete, data: { confirm: 'Are you sure?' } %></small>
</div>

app/views/interviews/_calendar.html.erb
<div class="col-lg-12">
<h3>Full List</h3>
<% @interviews.each do |interview| %>
<h3><%= interview.date_interviewed %>: <%= interview.kind %></h3>
<h4><%= interview.job.position %>: <%= interview.job.company %></h4>
<p><%= link_to "Notes", interview_path(interview) %></p>
<% end %>
</div>

app/views/interviews/_form.html.erb
<%= form_for([@application, @interview]) do |f| %>
<% if @interview.errors.any? %>
    <div id="error_explanation">
      <ul>
        <% @interview.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
        <% end %>
       </ul>
       </div>
       <% end %> 
  <div class="form-group">
    <%= f.label :date_interviewed %><br>
    <%= f.date_field :date_interviewed, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :interview_time %><br>
    <%= f.time_field :interview_time, class: "form-control" %>
  </div>  
  <div class="form-group">
    <div class="radio-inline">
      <%= f.radio_button :kind, 'Phone' %><b>Phone</b>
    </div>
    <div class="radio-inline">
      <%= f.radio_button :kind, 'In Person' %><b>In Person</b>
    </div>
    <div class="radio-inline">
      <%= f.radio_button :kind, 'Video Chat' %><b>Video</b>
    </div>
  </div> 
  <div class="form-group">
    <%= f.label :notes %><br>
    <%= f.text_area :notes, class: "form-control" %>
  </div> 
<div class="col-lg-12">      
  <div class="actions">
      <%= f.submit "Submit", class: "btn btn-large btn-primary" %>    
  </div> 
<% end %>

app/views/interviews/_list.html.erb
<div class="col-lg-12">
<h3>Full List</h3>
<% @interviews.each do |interview| %>
<h3><%= interview.date_interviewed %>: <%= interview.kind %></h3>
<h4><%= interview.application.position %>: <%= interview.application.company %></h4>
<p><%= link_to "Notes", interview_path(interview) %></p>
<% end %>
</div>

app/views/interviews/edit.html.erb
<h1>Edit Interview</h1>

<%= render 'form' %>

<div class="col-lg-12">
  <%= link_to 'Cancel', interview_path %>
</div>

app/views/interviews/index.html.erb
<h2>Interviews</h2>
<div id="interviews" class="col-lg-12">
<h2 id="month"class="col-lg-12">
  <span class="col-lg-1">
  <%= link_to "<", date: @date.prev_week %>
</span>
<span class="col-lg-10">
  <% date_range = @date.beginning_of_week..@date.end_of_week %>
  <%= date_range.to_s(:condensed) %>
</span>
<span class="col-lg-1">
  <%= link_to ">", date: @date.next_week %>
</span>
</h2>
<div class="table-responsive">
<%= calendar @date do |date| %>
  <%= date.day %>
  <% if @interviews_by_date[date] %>
    <ul>
      <% @interviews_by_date[date].sort_by! {|i| i.interview_time }.each do |interview| %>
        <li><%= interview.interview_time %>: <%= link_to interview.application.company, interview %> (<%= interview.kind %>)</li>
      <% end %>
    </ul>  
  <% end %>
<% end %>
</div>
</div>

app/views/interviews/new.html.erb
<h1>New Interview</h1>

<%= render 'form' %>

<div class="col-lg-12">
<%= link_to 'Cancel', application_path(@interview.application_id) %>
</div>

app/views/interviews/show.html.erb
<div class="col-lg-12">
  <h2>Interview: <%= @interview.date_interviewed %></h2>
  <h3><%= link_to @interview.application.position, application_path(@interview.application_id) %> - <%= @interview.application.company %></h3>
  <p>Time: <%= @interview.interview_time %></p>
  <p>Type: <%= @interview.kind %></p>
  <% if @interview.notes? %>
  <p>Notes: <%= simple_format @interview.notes %></p>
  <%= link_to "View Application", application_path(@interview.application_id) %>
  <% end %>
</div>
<div class="col-lg-12">
  <small>
    <%= link_to 'Edit', edit_interview_path %> | 
    <%= link_to 'Destroy', interview_path, method: :delete, data: { confirm: 'Are you sure?' } %>
  </small>
</div>

app/views/jobs/_form.html.erb
<%= form_for([@user, @job]) do |f| %>
<div class="col-lg-8">  
  <div class="form-group">
    <%= f.label :position %><br>
    <%= f.text_field :position, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :company %><br>
    <%= f.text_field :company, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :date_applied %><br>
    <%= f.date_field :date_applied, class: "form-control", input: "date" %>
  </div>  
  <div class="form-group">
    <%= f.label :link %><br>
    <%= f.text_field :link, class: "form-control" %>
  </div>  
  <div class="form-group">
    <%= f.label :description %><br>
    <%= f.text_area :description, class: "form-control", rows: "5" %>
  </div>
  <div class="form-group">
    <%= f.label :notes %><br>
    <%= f.text_area :notes, class: "form-control",  rows: "5" %>
  </div>       
  <h4>Contact Info</h4>
  <div class="form-group">
    <%= f.label :contact_name, "Name" %><br>
    <%= f.text_field :contact_name, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :contact_email, "Email" %><br>
    <%= f.text_field :contact_email, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :contact_phone, "Phone Number" %><br>
    <%= f.telephone_field :contact_phone, class: "form-control" %>
  </div>        
  <div class="form-group">
    <%= f.label :contact_address, "Address" %><br>
    <%= f.text_area :contact_address, class: "form-control",  rows: "3" %>
  </div>  
</div>         
<div class="col-lg-12">
    <%= f.submit "Submit", class: "btn btn-large btn-primary" %>    
</div>
<% end %>

app/views/jobs/new.html.erb
<title>Track new job application</title>
<h1>Track new job application</h1>

<%= render 'form' %>

<div class="col-lg-12">
<%= link_to 'Cancel', user_jobs_path(@user) %>
</div>

app/views/layouts/_footer.html.erb
<hr>
<p class="centered">Created with &#10084; by <%= link_to "Britney Wright", "http://www.twitter.com/britneywright", :target => "_blank" %></p>

app/views/layouts/_header.html.erb
<div class="navbar navbar-default navbar-fixed-top">
<div class="container">
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#global-nav">
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <a class="navbar-brand" href="/"><b>Track Apps</b></a>
  </div>
  <div class="collapse navbar-collapse" id="global-nav">
    <ul class="nav navbar-nav navbar-right">
  <li><%= render 'devise/menu/login_items' %></li>
    </ul>
  </div><!--/.nav-collapse -->
</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Track Apps | Track Job Applications & Interviews</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <link href='//fonts.googleapis.com/css?family=Lato:300,400,900' rel='stylesheet' type='text/css'>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <%= javascript_include_tag :modernizr %>
  <%= csrf_meta_tags %>
</head>

<body>
    <div id="wrap">
  <%= render 'layouts/header' %>
  <div class="container">
    <%= yield %>
      </div>
        </div>
        <div class="container">
    <%= render 'layouts/footer' %>
  </div>
</body>
</html>

app/views/layouts/home.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Track Apps | Track Job Applications & Interviews</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <link href='//fonts.googleapis.com/css?family=Lato:300,400,900' rel='stylesheet' type='text/css'>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <%= csrf_meta_tags %>
</head>

<body>
  <%= render 'layouts/header' %>
    <%= yield %>
  <%= render 'layouts/footer' %>
</body>
</html>

app/views/shared/_error_messages.html.erb
<% if @application.errors.any? %>
  <div id="error_explanation">
    <div class="alert text-danger">
      The form contains <%= pluralize(@application.errors.count, "error") %>.
    </div>
    <ul>
    <% @application.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %> 

app/views/static_pages/home.html.erb
<div id="headerwrap">
  <div class="container">
    <div class="row">
      <div class="col-lg-8">
        <h1>Keep Track of Your Job Applications & Interviews</h1>
          <% if user_signed_in? %>
            <%= link_to "View Applications", user_applications_path(current_user), class: "btn btn-warning btn-lg" %>
            <%= link_to "Track a new job application", new_user_application_path(current_user), class: "btn btn-warning btn-lg" %>
          <% else %>
            <%= link_to "Sign Up", new_user_registration_path, class: "btn btn-warning btn-lg" %>
          <% end %>       
      </div><!-- /col-lg-4 -->
      <div class="col-lg-4">
      </div><!-- /col-lg-4 -->
    </div><!-- /row -->
  </div><!-- /container -->
</div><!-- /headerwrap -->
  <div class="container">
    <div class="row mt centered">
      <div class="col-lg-8 col-lg-offset-2">
        <h1>Your Job Search Organized & Simplified</h1>
        <h3>Finding jobs to apply for is just the first part of the battle.<br/>Keeping up with every job application and interview is second.<br/>Track Apps will help your job hunt suck less.</h3>
      </div>
    </div><!-- /row -->

    <div class="row mt centered">
      <div class="col-lg-4">
        <%= image_tag('bookmark_handy-icon_01.png') %>
        <h4>Reading Done Right </h4>
        <p>Say bye, bye to spreadsheet cells and chicken scratch in different places. All your information in a clean, easy to follow, and read format.</p>
      </div><!--/col-lg-4 -->

      <div class="col-lg-4">
        <%= image_tag('calendar_handy-icon_04.png') %>
        <h4>Save the Date</h4>
        <p>Never forget when you applied for a job. When it's high tide for interviews get a weekly glance at what you've had and what's coming up.</p>

      </div><!--/col-lg-4 -->

      <div class="col-lg-4">
        <%= image_tag('phone_handy-icon_03.png') %>
        <h4>Logs Anywhere, Anytime</h4>
        <p>Simple, responsive design allows you to view your data on any device. Handy when you need to quickly review a job before your next interview.</p>

      </div><!--/col-lg-4 -->
    </div><!-- /row -->
  </div><!-- /container -->
  <div class="container">
    <hr>
    <div class="row centered">
      <div class="col-lg-6 col-lg-offset-3">
          <%= link_to "Get Tracking", new_user_registration_path, class: "btn btn-warning btn-lg" %>        
      </div>
      <div class="col-lg-3"></div>
    </div><!-- /row -->     